# Generated by Django 6.0.6 on 2026-07-04 20:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tn_ancestors_pks', models.TextField(blank=True, default='', editable=False, verbose_name='Ancestors pks')),
                ('tn_ancestors_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Ancestors count')),
                ('tn_children_pks', models.TextField(blank=True, default='', editable=False, verbose_name='Children pks')),
                ('tn_children_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Children count')),
                ('tn_depth', models.PositiveIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Depth')),
                ('tn_descendants_pks', models.TextField(blank=True, default='', editable=False, verbose_name='Descendants pks')),
                ('tn_descendants_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Descendants count')),
                ('tn_index', models.PositiveIntegerField(default=0, editable=False, verbose_name='Index')),
                ('tn_level', models.PositiveIntegerField(default=1, editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Level')),
                ('tn_priority', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Priority')),
                ('tn_order', models.PositiveIntegerField(default=0, editable=False, verbose_name='Order')),
                ('tn_siblings_pks', models.TextField(blank=True, default='', editable=False, verbose_name='Siblings pks')),
                ('tn_siblings_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Siblings count')),
                ('revision', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(db_index=True, max_length=100, unique=True)),
                ('comment', models.CharField(blank=True, default='', help_text='Comment for translators', max_length=255)),
                ('draft', models.TextField(blank=True, default='')),
                ('catalog_icon', models.CharField(blank=True, default='', help_text='CDN catalog icon reference (opaque string, e.g. catalog/asset-name)', max_length=255)),
                ('carousel_icon', models.CharField(blank=True, default='', help_text='CDN carousel icon reference (opaque string, e.g. carousel/asset-name)', max_length=255)),
                ('carousel_enabled', models.BooleanField(default=False, help_text='Whether this category appears in the carousel')),
                ('active', models.BooleanField(default=True, help_text='Whether this category is active')),
                ('translatable', models.BooleanField(default=True, help_text='If True, category name is a translation key')),
                ('tn_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tn_children', to='categories.category', verbose_name='Parent')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tn_ancestors_pks', models.TextField(blank=True, default='', editable=False, verbose_name='Ancestors pks')),
                ('tn_ancestors_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Ancestors count')),
                ('tn_children_pks', models.TextField(blank=True, default='', editable=False, verbose_name='Children pks')),
                ('tn_children_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Children count')),
                ('tn_depth', models.PositiveIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Depth')),
                ('tn_descendants_pks', models.TextField(blank=True, default='', editable=False, verbose_name='Descendants pks')),
                ('tn_descendants_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Descendants count')),
                ('tn_index', models.PositiveIntegerField(default=0, editable=False, verbose_name='Index')),
                ('tn_level', models.PositiveIntegerField(default=1, editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Level')),
                ('tn_priority', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Priority')),
                ('tn_order', models.PositiveIntegerField(default=0, editable=False, verbose_name='Order')),
                ('tn_siblings_pks', models.TextField(blank=True, default='', editable=False, verbose_name='Siblings pks')),
                ('tn_siblings_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Siblings count')),
                ('revision', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(blank=True, default='', max_length=100)),
                ('icon', models.CharField(blank=True, default='', max_length=255)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('config', models.JSONField(blank=True, default=dict, help_text="Type-specific configuration. Must include 'type'. Validated by stapel-attributes.")),
                ('mandatory', models.BooleanField(default=False)),
                ('show_as_badge', models.BooleanField(default=False)),
                ('show_at_title', models.BooleanField(default=False)),
                ('translate', models.CharField(choices=[('all', 'All (title + options)'), ('title', 'Title only'), ('none', 'None')], default='all', help_text="What to translate: 'all' = title + options, 'title' = title only, 'none' = nothing", max_length=10)),
                ('tn_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tn_children', to='categories.feature', verbose_name='Parent')),
            ],
            options={
                'ordering': ['tn_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_features', to='categories.category')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_categories', to='categories.feature')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='categories', through='categories.CategoryFeature', through_fields=('category', 'feature'), to='categories.feature'),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['revision'], name='cat_feature_revision_idx'),
        ),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.UniqueConstraint(condition=models.Q(('tn_parent__isnull', True), models.Q(('slug', ''), _negated=True)), fields=('slug',), name='categories_feature_root_slug_unique'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryfeature',
            unique_together={('category', 'feature')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['revision'], name='cat_category_revision_idx'),
        ),
    ]
