# Generated by Django 6.0.6 on 2026-07-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False, help_text='Test/scratch data — excluded from export_catalog fixtures.'),
        ),
        migrations.AddField(
            model_name='feature',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False, help_text='Test/scratch data — excluded from export_catalog fixtures.'),
        ),
    ]
