# Generated by Django 6.0.7 on 2026-08-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_is_test_feature_is_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Identifier in the source catalogue this category was imported from.', max_length=64),
        ),
        migrations.AddField(
            model_name='feature',
            name='default',
            field=models.JSONField(blank=True, help_text="Initial form value in DTO 'value' shape (for a select, a list of option codes).", null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Help text under the field; translation key or literal.'),
        ),
        migrations.AddField(
            model_name='feature',
            name='example',
            field=models.CharField(blank=True, default='', help_text='Placeholder text; translation key or literal.', max_length=255),
        ),
        migrations.AddField(
            model_name='feature',
            name='group',
            field=models.CharField(blank=True, default='', help_text='Form section; sections order by first appearance.', max_length=100),
        ),
        migrations.AddField(
            model_name='feature',
            name='hints',
            field=models.JSONField(blank=True, default=list, help_text='Notices rendered with the field: [{"title": ..., "content": ...}].'),
        ),
        migrations.AddField(
            model_name='feature',
            name='rules',
            field=models.JSONField(blank=True, default=list, help_text='Conditional rules (closed grammar). Validated by stapel-attributes.'),
        ),
    ]
