# Generated by Django 6.0.8 on 2026-08-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_feature_rules_form_metadata_category_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='external_source',
            field=models.CharField(blank=True, default='', help_text='Source catalogue `external_id` belongs to (blank = the single/default source).', max_length=32),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['external_source', 'external_id'], name='cat_category_extid_idx'),
        ),
    ]
