# Generated by Django 6.0.8 on 2026-09-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_category_external_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public — anyone may read the value'), ('owner', 'Owner (and staff)'), ('staff', 'Staff only')], default='public', help_text="Who may READ a stored value: 'public' = anyone (the default), 'owner' = the object's owner and staff, 'staff' = staff only. The value is still required, validated and stored either way. A non-public feature is never a title and never a badge.", max_length=10),
        ),
    ]
