# Generated by Django 6.0.7 on 2026-09-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_feature_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='children_as',
            field=models.CharField(choices=[('auto', 'Auto (derive)'), ('tiles', 'Tiles'), ('chips', 'Chips')], default='auto', help_text="Authored presentation of this category's children: `auto` (derive), `tiles` (real subcategories) or `chips` (a partition of one attribute template). An authored value wins over derivation.", max_length=8),
        ),
        migrations.AddField(
            model_name='category',
            name='children_as_derived',
            field=models.CharField(blank=True, choices=[('tiles', 'Tiles'), ('chips', 'Chips')], default='', editable=False, help_text='Cache of `derive_children_as --apply`. Read only when `children_as` is `auto`; never overwrites an authored value.', max_length=8),
        ),
    ]
