# Generated by Django 6.0.8 on 2026-09-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_category_children_as'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='children_axis_label',
            field=models.CharField(blank=True, default='', help_text="Name of the axis this category's children split on (e.g. a key rendering as 'Condition' over New | Used). Translation key, like `name`. Empty means the chip row is drawn uncaptioned.", max_length=200),
        ),
    ]
