# Generated by Django 6.0.7 on 2026-09-04 21:24
#
# Additive only: one more choice (`transparent`) and the width to hold it
# (8 -> 16). Widening a varchar keeps every stored value valid, so this is an
# EXPAND step with no contract half — no data migration, nothing to backfill.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_category_children_axis_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='children_as',
            field=models.CharField(choices=[('auto', 'Auto (derive)'), ('tiles', 'Tiles'), ('chips', 'Chips'), ('transparent', 'Transparent (browsing skips this level)')], default='auto', help_text="Authored presentation of this category's children: `auto` (derive), `tiles` (real subcategories), `chips` (a partition of one attribute template) or `transparent` (browsing skips this node — its children appear where it would). An authored value wins over derivation.", max_length=16),
        ),
    ]
