# Generated by Django 6.0.8 on 2026-09-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_category_children_as_transparent'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='axis_role',
            field=models.CharField(blank=True, choices=[('make', 'Make (brand / vendor / manufacturer)'), ('model', 'Model'), ('generation', 'Generation'), ('year', 'Year of manufacture'), ('mileage', 'Mileage')], default='', help_text="Which classified axis this feature IS, when it is one: `make`, `model`, `generation`, `year`, `mileage`. Blank (the default) for the overwhelming majority of features, which describe an object rather than organise it. An authored value wins over the loader's derivation.", max_length=16),
        ),
        migrations.AddField(
            model_name='feature',
            name='axis_role_derived',
            field=models.CharField(blank=True, choices=[('make', 'Make (brand / vendor / manufacturer)'), ('model', 'Model'), ('generation', 'Generation'), ('year', 'Year of manufacture'), ('mileage', 'Mileage')], default='', editable=False, help_text="Cache of `load_catalog`'s slug-table derivation. Read only when `axis_role` is blank; never overwrites an authored value.", max_length=16),
        ),
    ]
